### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ottopodo** [ndum/laravel-snmp#1]
Hello,
could you please post an example?
The documentation is covering  FreeDSx/SNMP but the wrapper is using different methods.

**Comment by ndum** [comment]
Hi!

I'm currently on vacation. I'll give you an example as soon as I get back ;)

**Comment by ndum** [comment]
Hi...

Sorry for the long delay, vacation and corona at the same time is difficult ;)

If u still want to use this package, some examples are now [provided](https://github.com/ndum/laravel-snmp#examples).

**Comment by Tahernejad** [comment]
Hi,
any example of 'timeout_connect' and 'timeout_read' please ?
Thanks

**Comment by ndum** [comment]
Hi!

This is currently not possible, I will add it this week. (with examples)

**Comment by ndum** [comment]
I just realeased version [1.5.0](https://github.com/ndum/laravel-snmp/releases/tag/1.5.0). It's now possible to set both timeout-options

Examples are here: https://github.com/ndum/laravel-snmp#extras
