### ISSUE TITLE
SNMP Traps

### ISSUE THREAD

**Issue by CrawDance** [ndum/laravel-snmp#6]
to whom it my concern, wish you all the bests and thanks for the great package.

I want to know is there any plan for SNMP traps to be included in the package? if it is, when will it be ?

Thanks in advance.

**Comment by ndum** [comment]
Hello!

Thanks for the feedback!

SNMP traps are a important feature on my backlog. I'll try to implement it over the next few weeks.

I hope that helps you as an approximate schedule ;)

**Comment by CrawDance** [comment]
Thanks for the response!
I'll be waiting for the next release.

Thanks.

**Comment by ndum** [comment]
Hi! Im finally got around to adding support for SNMP-Traps (sending & receiving)

Release: https://github.com/ndum/laravel-snmp/releases/tag/1.6.1

Docs: https://github.com/ndum/laravel-snmp#extras
