### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by Tahernejad** [ndum/laravel-snmp#8]
Hi
Cannot install on laravel 10.13.0

`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires ndum/laravel-snmp 1.8.* -> satisfiable by ndum/laravel-snmp[1.8.0].
    - ndum/laravel-snmp 1.8.0 requires illuminate/support ~5.5|~6.0|~7.0|~8.0|~9.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.8] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

**Comment by ndum** [comment]
Hi @Tahernejad 

I will look at it later today. Should be simple to fix ;)

**Comment by ndum** [comment]
Hi @Tahernejad

I have just released version [1.9.0](https://github.com/ndum/laravel-snmp/releases/tag/1.9.0)

This version now works with Laravel 10 as well.
